'use client';

import { useRouter } from 'next/navigation';
import { AlertTriangle, Zap, AlertCircle, TrendingUp } from 'lucide-react';
import { useCity } from '@/contexts/city-context';
import { dataService } from '@/lib/data-service';

/**
 * SUMMARY CARDS - SINGLE SOURCE OF TRUTH
 * 
 * CRITICAL: These cards use dataService.getDashboardStats() which uses
 * the EXACT SAME filtering logic as the detail pages.
 * 
 * Click-through contract: Navigation URLs are generated by dataService
 * to ensure consistent filter parameters.
 */
export function SummaryCards() {
  const router = useRouter();
  const { selectedCity } = useCity();

  if (!selectedCity) {
    return (
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        {[...Array(4)].map((_, idx) => (
          <div
            key={idx}
            className="bg-card border border-border rounded-lg p-6 animate-pulse"
          >
            <div className="h-4 bg-muted rounded mb-4"></div>
            <div className="h-8 bg-muted rounded mb-3"></div>
            <div className="h-1 bg-muted rounded"></div>
          </div>
        ))}
      </div>
    );
  }

  // ✅ SINGLE SOURCE OF TRUTH: Use dataService for all statistics
  const stats = dataService.getDashboardStats(selectedCity.name);
  const navigationUrls = dataService.getNavigationUrls(selectedCity.name);

  const cards = [
    {
      title: 'Total Potholes',
      value: stats.totalPotholes,
      icon: AlertCircle,
      color: 'from-blue-500/20 to-cyan-500/20',
      textColor: 'text-cyan-400',
      borderColor: 'border-cyan-500/30',
      onClick: () => router.push(navigationUrls.totalPotholes),
      description: `All potholes in ${selectedCity.name}`
    },
    {
      title: 'High-Risk Potholes',
      value: stats.highRiskPotholes,
      icon: AlertTriangle,
      color: 'from-red-500/20 to-orange-500/20',
      textColor: 'text-orange-400',
      borderColor: 'border-orange-500/30',
      onClick: () => router.push(navigationUrls.highRiskPotholes),
      description: `Severity = high in ${selectedCity.name}`
    },
    {
      title: 'Roads Needing Repair',
      value: stats.roadsNeedingRepair,
      icon: TrendingUp,
      color: 'from-yellow-500/20 to-amber-500/20',
      textColor: 'text-yellow-400',
      borderColor: 'border-yellow-500/30',
      onClick: () => router.push(navigationUrls.roadsNeedingRepair),
      description: `Health score < 50% in ${selectedCity.name}`
    },
    {
      title: 'Avg Road Health',
      value: `${stats.averageRoadHealth}%`,
      icon: Zap,
      color: 'from-green-500/20 to-emerald-500/20',
      textColor: 'text-green-400',
      borderColor: 'border-green-500/30',
      onClick: () => router.push(navigationUrls.averageRoadHealth),
      description: `Average across all roads in ${selectedCity.name}`
    },
  ];

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
      {cards.map((card, idx) => {
        const Icon = card.icon;
        return (
          <div
            key={idx}
            onClick={card.onClick}
            className={`bg-gradient-to-br ${card.color} border ${card.borderColor} rounded-lg p-6 backdrop-blur-sm transition-all hover:shadow-lg hover:shadow-cyan-500/20 cursor-pointer hover:scale-105 group`}
          >
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-medium text-foreground/80 group-hover:text-foreground transition-colors">
                {card.title}
              </h3>
              <Icon className={`w-5 h-5 ${card.textColor} group-hover:scale-110 transition-transform`} />
            </div>
            <p className={`text-3xl font-bold ${card.textColor} mb-2`}>
              {card.value}
            </p>
            <div className="mt-3 h-1 bg-gradient-to-r from-primary to-accent rounded-full group-hover:h-1.5 transition-all" />
            <p className="text-xs text-foreground/50 mt-2 group-hover:text-foreground/70 transition-colors">
              {card.description}
            </p>
            <p className="text-xs text-foreground/40 mt-1">
              Click to view details →
            </p>
          </div>
        );
      })}
    </div>
  );
}
